apiVersion: v1
kind: Pod
metadata:
  name: imageinfo-pod
  #namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
      containers:
      - name: imageinfo
        args:
        #- -c
        #- docker inspect $(docker images --no-trunc -aq) && sleep 50
        command:
        - env #/bin/sh
        env:
        - name: DOCKER_API_VERSION
          value: "1.23"
        image: docker:17.03
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run
        name: docker-sock
